### ISSUE TITLE
TypeError: 'list' object is not callable

### ISSUE THREAD

**Issue by M2shad0w** [siddhantgoel/tornado-sqlalchemy#48]
when i use

```
 yield as_future(self.session.query(Prop.title, Prop.image_path, Prop.discount_price).all())
```
meet this error
```
Traceback (most recent call last):
  File "/home/m2/anaconda2/envs/py36/lib/python3.6/site-packages/tornado/web.py", line 1592, in _execute
    result = yield result
  File "/home/m2/anaconda2/envs/py36/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/home/m2/anaconda2/envs/py36/lib/python3.6/site-packages/tornado/gen.py", line 1141, in run
    yielded = self.gen.throw(*exc_info)
  File "/home/m2/gitdoc/server/handlers/property.py", line 44, in get
    .query(Prop.title, Prop.image_path, Prop.discount_price)
  File "/home/m2/anaconda2/envs/py36/lib/python3.6/site-packages/tornado/gen.py", line 1133, in run
    value = future.result()
  File "/home/m2/anaconda2/envs/py36/lib/python3.6/concurrent/futures/thread.py", line 56, in run
    result = self.fn(*self.args, **self.kwargs)
TypeError: 'list' object is not callable

```

but `self.session.query(Prop.title, Prop.image_path, Prop.discount_price).all()` is fine

**Comment by siddhantgoel** [comment]
Try ` yield as_future(self.session.query(Prop.title, Prop.image_path, Prop.discount_price).all)`

**Comment by M2shad0w** [comment]
> Try ` yield as_future(self.session.query(Prop.title, Prop.image_path, Prop.discount_price).all)`

this is ok，but how to slice like `.filter(Prop.property == pro)[page*limit:(page+1)*limit]`

**Comment by siddhantgoel** [comment]
`yield as_future(self.session.query(Prop.title, Prop.image_path, Prop.discount_price).filter(Prop.property == pro).limit(x).offset(y).all)` should also work. It should be possible to calculate `x` and `y` from the `page` and `limit` variables. It's better anyway to do the pagination at the database level instead of on Python objects.

**Comment by siddhantgoel** [comment]
@M2shad0w I've closed this issue for now. If you have more questions, feel free to reopen.
